// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJEGtqKavYa85ER4474bc7NXOqhQsIM20',
    appId: '1:376103100127:web:7df469ca42a80e6171536a',
    messagingSenderId: '376103100127',
    projectId: 'chatapp-ee215',
    authDomain: 'chatapp-ee215.firebaseapp.com',
    storageBucket: 'chatapp-ee215.appspot.com',
    measurementId: 'G-N6E35PGJ1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy2Ic9vv6ED5qS6SiiIp3lAEtZZScFWl8',
    appId: '1:376103100127:android:5785c272c26ad07871536a',
    messagingSenderId: '376103100127',
    projectId: 'chatapp-ee215',
    storageBucket: 'chatapp-ee215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4JLWEiRvOWRn-a9FnWhiwedXfP7wLhRA',
    appId: '1:376103100127:ios:c2e28ce338cdfe8471536a',
    messagingSenderId: '376103100127',
    projectId: 'chatapp-ee215',
    storageBucket: 'chatapp-ee215.appspot.com',
    iosClientId:
        '376103100127-p5ng5lbbjsjuliqvbh5kti1oor8ntsk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
